/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appcalc;

import java.awt.Color;

/**
 *
 * @author Dell
 */
public class AppCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form AppCalculadora
     */
    public AppCalculadora() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    double valor1, valor2, soma, sub, mult, div, porc, potencia, fator;
    String sinal, sinal2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JTextField();
        numZero = new javax.swing.JButton();
        numUm = new javax.swing.JButton();
        numDois = new javax.swing.JButton();
        numTres = new javax.swing.JButton();
        numQuatro = new javax.swing.JButton();
        numCinco = new javax.swing.JButton();
        numSeis = new javax.swing.JButton();
        numSete = new javax.swing.JButton();
        numOito = new javax.swing.JButton();
        numNove = new javax.swing.JButton();
        bntPONTO = new javax.swing.JButton();
        bntIGUAL = new javax.swing.JButton();
        bntADICAO = new javax.swing.JButton();
        bntSUB = new javax.swing.JButton();
        bntMULT = new javax.swing.JButton();
        bntDIVISAO = new javax.swing.JButton();
        bntOnOff = new javax.swing.JButton();
        tfPotencia = new javax.swing.JButton();
        bntPorcentagem = new javax.swing.JButton();
        bntCLEAR = new javax.swing.JButton();
        fatoracao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA JAVA - v.2023");

        display.setEditable(false);
        display.setFont(new java.awt.Font("Algerian", 0, 20)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        numZero.setBackground(new java.awt.Color(0, 0, 0));
        numZero.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numZero.setForeground(new java.awt.Color(255, 255, 255));
        numZero.setText("0");
        numZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numZeroActionPerformed(evt);
            }
        });

        numUm.setBackground(new java.awt.Color(0, 0, 0));
        numUm.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numUm.setForeground(new java.awt.Color(255, 255, 255));
        numUm.setText("1");
        numUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numUmActionPerformed(evt);
            }
        });

        numDois.setBackground(new java.awt.Color(0, 0, 0));
        numDois.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numDois.setForeground(new java.awt.Color(255, 255, 255));
        numDois.setText("2");
        numDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDoisActionPerformed(evt);
            }
        });

        numTres.setBackground(new java.awt.Color(0, 0, 0));
        numTres.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numTres.setForeground(new java.awt.Color(255, 255, 255));
        numTres.setText("3");
        numTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTresActionPerformed(evt);
            }
        });

        numQuatro.setBackground(new java.awt.Color(0, 0, 0));
        numQuatro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numQuatro.setForeground(new java.awt.Color(255, 255, 255));
        numQuatro.setText("4");
        numQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numQuatroActionPerformed(evt);
            }
        });

        numCinco.setBackground(new java.awt.Color(0, 0, 0));
        numCinco.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numCinco.setForeground(new java.awt.Color(255, 255, 255));
        numCinco.setText("5");
        numCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCincoActionPerformed(evt);
            }
        });

        numSeis.setBackground(new java.awt.Color(0, 0, 0));
        numSeis.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numSeis.setForeground(new java.awt.Color(255, 255, 255));
        numSeis.setText("6");
        numSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSeisActionPerformed(evt);
            }
        });

        numSete.setBackground(new java.awt.Color(0, 0, 0));
        numSete.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numSete.setForeground(new java.awt.Color(255, 255, 255));
        numSete.setText("7");
        numSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSeteActionPerformed(evt);
            }
        });

        numOito.setBackground(new java.awt.Color(0, 0, 0));
        numOito.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numOito.setForeground(new java.awt.Color(255, 255, 255));
        numOito.setText("8");
        numOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOitoActionPerformed(evt);
            }
        });

        numNove.setBackground(new java.awt.Color(0, 0, 0));
        numNove.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        numNove.setForeground(new java.awt.Color(255, 255, 255));
        numNove.setText("9");
        numNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numNoveActionPerformed(evt);
            }
        });

        bntPONTO.setBackground(new java.awt.Color(0, 102, 102));
        bntPONTO.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntPONTO.setForeground(new java.awt.Color(0, 0, 0));
        bntPONTO.setText(".");
        bntPONTO.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bntPONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPONTOActionPerformed(evt);
            }
        });

        bntIGUAL.setBackground(new java.awt.Color(204, 102, 0));
        bntIGUAL.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntIGUAL.setForeground(new java.awt.Color(0, 0, 0));
        bntIGUAL.setText("=");
        bntIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIGUALActionPerformed(evt);
            }
        });

        bntADICAO.setBackground(new java.awt.Color(51, 102, 0));
        bntADICAO.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntADICAO.setForeground(new java.awt.Color(0, 0, 0));
        bntADICAO.setText("+");
        bntADICAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntADICAOActionPerformed(evt);
            }
        });

        bntSUB.setBackground(new java.awt.Color(51, 102, 0));
        bntSUB.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntSUB.setForeground(new java.awt.Color(0, 0, 0));
        bntSUB.setText("–");
        bntSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSUBActionPerformed(evt);
            }
        });

        bntMULT.setBackground(new java.awt.Color(51, 102, 0));
        bntMULT.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntMULT.setForeground(new java.awt.Color(0, 0, 0));
        bntMULT.setText("×");
        bntMULT.setToolTipText("");
        bntMULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMULTActionPerformed(evt);
            }
        });

        bntDIVISAO.setBackground(new java.awt.Color(51, 102, 0));
        bntDIVISAO.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bntDIVISAO.setForeground(new java.awt.Color(0, 0, 0));
        bntDIVISAO.setText("÷");
        bntDIVISAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDIVISAOActionPerformed(evt);
            }
        });

        bntOnOff.setBackground(new java.awt.Color(0, 102, 204));
        bntOnOff.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        bntOnOff.setForeground(new java.awt.Color(0, 0, 0));
        bntOnOff.setText("ON/OFF");
        bntOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOnOffActionPerformed(evt);
            }
        });

        tfPotencia.setBackground(new java.awt.Color(0, 102, 204));
        tfPotencia.setFont(new java.awt.Font("Impact", 1, 10)); // NOI18N
        tfPotencia.setForeground(new java.awt.Color(0, 0, 0));
        tfPotencia.setText("^");
        tfPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPotenciaActionPerformed(evt);
            }
        });

        bntPorcentagem.setBackground(new java.awt.Color(0, 102, 204));
        bntPorcentagem.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        bntPorcentagem.setForeground(new java.awt.Color(0, 0, 0));
        bntPorcentagem.setText("%");
        bntPorcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntPorcentagemMouseClicked(evt);
            }
        });
        bntPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPorcentagemActionPerformed(evt);
            }
        });
        bntPorcentagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntPorcentagemKeyPressed(evt);
            }
        });

        bntCLEAR.setBackground(new java.awt.Color(0, 102, 204));
        bntCLEAR.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        bntCLEAR.setForeground(new java.awt.Color(0, 0, 0));
        bntCLEAR.setText("CE");
        bntCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCLEARActionPerformed(evt);
            }
        });

        fatoracao.setBackground(new java.awt.Color(0, 102, 204));
        fatoracao.setFont(new java.awt.Font("Impact", 1, 10)); // NOI18N
        fatoracao.setForeground(new java.awt.Color(0, 0, 0));
        fatoracao.setText("!");
        fatoracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatoracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(display)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(numUm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(numDois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(numTres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(bntPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bntIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numSete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numOito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numNove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(bntADICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bntMULT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bntDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bntSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bntCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fatoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bntPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bntOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numSete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numNove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numUm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numDois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntMULT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntADICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDoisActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "2");
    }//GEN-LAST:event_numDoisActionPerformed

    private void numUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numUmActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "1");
    }//GEN-LAST:event_numUmActionPerformed

    private void numZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numZeroActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "0");
    }//GEN-LAST:event_numZeroActionPerformed

    private void numTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTresActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "3");
    }//GEN-LAST:event_numTresActionPerformed

    private void numQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numQuatroActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "4");
    }//GEN-LAST:event_numQuatroActionPerformed

    private void numCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCincoActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "5");
    }//GEN-LAST:event_numCincoActionPerformed

    private void numSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSeisActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "6");
    }//GEN-LAST:event_numSeisActionPerformed

    private void numSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSeteActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "7");
    }//GEN-LAST:event_numSeteActionPerformed

    private void numOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOitoActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "8");
    }//GEN-LAST:event_numOitoActionPerformed

    private void numNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numNoveActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + "9");
    }//GEN-LAST:event_numNoveActionPerformed

    private void bntPONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPONTOActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + ".");
    }//GEN-LAST:event_bntPONTOActionPerformed

    private void bntADICAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntADICAOActionPerformed
        // TODO add your handling code here:    
        valor1 = Double.parseDouble(display.getText());
        sinal = " + ";
        display.setText("");
    }//GEN-LAST:event_bntADICAOActionPerformed

    private void bntIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIGUALActionPerformed
        // TODO add your handling code here:
        valor2 = Double.parseDouble(display.getText());
        if (sinal == " + ") {
            soma = valor1 + valor2;
            display.setText(((int) valor1) + sinal + (int) valor2 + " = " + (int) soma);
        } else if (sinal == " - ") {
            sub = valor1 - valor2;
            display.setText((int) valor1 + sinal + (int) valor2 + " = " + (int) sub);
        } else if (sinal == " × ") {
            mult = valor1 * valor2;
            display.setText((int) valor1 + sinal + (int) valor2 + " = " + (int) mult);
        } else if (sinal == " ÷ ") {
            try {
                div = valor1 / valor2;
                display.setText(valor1 + sinal + valor2 + " = " + String.valueOf(div).format("%.2f", div));
            } catch (Exception erro) {
            }
        } else if (sinal == " % ") {
            porc = valor1 * valor2 / 100;
            display.setText(valor1 + sinal + valor2 + " = " + String.valueOf(porc).format("%.2f", porc));
        }
        else
            if (sinal == " ^ "){
                potencia = Math.pow(valor1,valor2);
                display.setText((int)valor1 + sinal + (int)valor2 + " = " + (int)potencia);
            }
    }//GEN-LAST:event_bntIGUALActionPerformed

    private void bntSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSUBActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(display.getText());
        sinal = " - ";
        display.setText("");
    }//GEN-LAST:event_bntSUBActionPerformed

    private void bntMULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMULTActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(display.getText());
        sinal = " × ";
        display.setText("");
    }//GEN-LAST:event_bntMULTActionPerformed

    private void bntDIVISAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDIVISAOActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(display.getText());
        sinal = " ÷ ";
        display.setText("");
    }//GEN-LAST:event_bntDIVISAOActionPerformed

    private void tfPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPotenciaActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(display.getText());
        sinal = " ^ ";
        display.setText("");
    }//GEN-LAST:event_tfPotenciaActionPerformed

    private void bntCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCLEARActionPerformed
        // TODO add your handling code here:
        display.setText("");
    }//GEN-LAST:event_bntCLEARActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void bntPorcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPorcentagemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPorcentagemMouseClicked

    private void bntPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPorcentagemActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(display.getText());
        sinal = " % ";
        display.setText("");

    }//GEN-LAST:event_bntPorcentagemActionPerformed

    private void bntPorcentagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntPorcentagemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPorcentagemKeyPressed

    private void bntOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOnOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntOnOffActionPerformed

    private void fatoracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatoracaoActionPerformed
        // TODO add your handling code here:
        valor1 = Integer.parseInt(display.getText());
        for (int i = 1; i <= valor1; i++){
            double fator = i * valor1;
        }
    }//GEN-LAST:event_fatoracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntADICAO;
    private javax.swing.JButton bntCLEAR;
    private javax.swing.JButton bntDIVISAO;
    private javax.swing.JButton bntIGUAL;
    private javax.swing.JButton bntMULT;
    private javax.swing.JButton bntOnOff;
    private javax.swing.JButton bntPONTO;
    private javax.swing.JButton bntPorcentagem;
    private javax.swing.JButton bntSUB;
    private javax.swing.JTextField display;
    private javax.swing.JButton fatoracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numCinco;
    private javax.swing.JButton numDois;
    private javax.swing.JButton numNove;
    private javax.swing.JButton numOito;
    private javax.swing.JButton numQuatro;
    private javax.swing.JButton numSeis;
    private javax.swing.JButton numSete;
    private javax.swing.JButton numTres;
    private javax.swing.JButton numUm;
    private javax.swing.JButton numZero;
    private javax.swing.JButton tfPotencia;
    // End of variables declaration//GEN-END:variables
}
