/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appcalc;

import appcalc.AppMediaNota;

/**
 *
 * @author Blade CVA120
 */
public class Container extends javax.swing.JFrame {
    

    /**
     * Creates new form Container
     */
    public Container() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntMedia = new javax.swing.JButton();
        bntIMC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntBhask = new javax.swing.JButton();
        bntCalc = new javax.swing.JButton();
        bntTab = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 4));

        bntMedia.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bntMedia.setForeground(new java.awt.Color(0, 0, 0));
        bntMedia.setText("Média de Notas");
        bntMedia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMediaActionPerformed(evt);
            }
        });

        bntIMC.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bntIMC.setForeground(new java.awt.Color(0, 0, 0));
        bntIMC.setText("Índice de Massa Corporal");
        bntIMC.setToolTipText("");
        bntIMC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntIMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntIMCMouseClicked(evt);
            }
        });
        bntIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIMCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AppCalc");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 4));

        bntBhask.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bntBhask.setForeground(new java.awt.Color(0, 0, 0));
        bntBhask.setText("Fórmula de Bháskara");
        bntBhask.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntBhask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBhaskActionPerformed(evt);
            }
        });

        bntCalc.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bntCalc.setForeground(new java.awt.Color(0, 0, 0));
        bntCalc.setText("Calculadora");
        bntCalc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcActionPerformed(evt);
            }
        });

        bntTab.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bntTab.setForeground(new java.awt.Color(0, 0, 0));
        bntTab.setText("Tabuada");
        bntTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bntSair.setBackground(new java.awt.Color(0, 153, 0));
        bntSair.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        bntSair.setForeground(new java.awt.Color(0, 0, 0));
        bntSair.setText("SAIR");
        bntSair.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));
        bntSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bntIMC)
                    .addComponent(bntBhask)
                    .addComponent(bntMedia)
                    .addComponent(bntCalc)
                    .addComponent(bntTab)
                    .addComponent(bntSair, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(bntIMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntBhask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntSair)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBhaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBhaskActionPerformed
        // TODO add your handling code here:
        new AppBhaskara().setVisible(true);
    }//GEN-LAST:event_bntBhaskActionPerformed

    private void bntIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIMCActionPerformed
        // TODO add your handling code here:        
        new AppIMC().setVisible(true);

    }//GEN-LAST:event_bntIMCActionPerformed

    private void bntIMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntIMCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bntIMCMouseClicked

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bntSairActionPerformed

    private void bntMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMediaActionPerformed
        // TODO add your handling code here:
        new AppMediaNota().setVisible(true);
    }//GEN-LAST:event_bntMediaActionPerformed

    private void bntCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcActionPerformed
        // TODO add your handling code here:
        new AppCalculadora().setVisible(true);
    }//GEN-LAST:event_bntCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Container().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBhask;
    private javax.swing.JButton bntCalc;
    private javax.swing.JButton bntIMC;
    private javax.swing.JButton bntMedia;
    private javax.swing.JButton bntSair;
    private javax.swing.JButton bntTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
